Repository DDu-Du-DDu-Du/back-end, pull requests merged in 2023-12, with the labels that each got.

#2 Chore/configure db
  scripts/docker-test.sh
  scripts/local/Dockerfile
  scripts/local/docker-local.sh
  scripts/local/schema.sql
  src/main/resources/application-local.yaml
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/test/resources/application.yaml
Labels: ⚙setting

#5 flyway를 사용해서 DB 마이그레이션 진행
  build.gradle
  scripts/local/Dockerfile
  src/main/resources/application-local.yaml
  src/main/resources/db/data/afterMigrate.sql
  src/main/resources/db/migration/V1__schema.sql
  src/test/resources/application.yaml
Labels: ⚙setting

#7 CI 파이프라인 구축
  .github/workflows/ci-pipeline.yaml
  scripts/docker-local.sh
  scripts/docker-test.sh
Labels: ⚙setting

#10 CheckStyle 적용
  config/checkstyle/checkstyle.xml
  config/checkstyle/suppressions.xml
Labels: ⚙setting

#12 도커 구동 스크립트에 MySQL이 켜질 때까지 대기하는 스크립트 추가
  scripts/docker-local.sh
Labels: ⚙setting

#18 feat: api 요청 시 필요 없는 필터 무시
  src/main/java/com/ddudu/config/WebSecurityConfig.java
Labels: ✨feature

#24 CI 파이프라인 개선
  .github/workflows/ci-pipeline.yaml
Labels: ⚙setting

#27 Dockerfile에 DB 타임존 서울로 추가
  scripts/local/Dockerfile
Labels: ⚙setting

#29 체크스타일 메서드 명과 타입 명 한글 허용
  .github/workflows/ci-pipeline.yaml
  build.gradle
  config/checkstyle/checkstyle.xml
  src/test/java/com/ddudu/DduduApplicationTests.java
Labels: ⚙setting

#36 Checkstyle 연속적인 대문자 허용
  config/checkstyle/checkstyle.xml
Labels: ⚙setting

#33 할 일 1개(단일) 조회 기능 구현
  src/main/java/com/ddudu/goal/domain/Goal.java
  src/main/java/com/ddudu/goal/repository/GoalRepository.java
  src/main/java/com/ddudu/todo/controller/TodoController.java
  src/main/java/com/ddudu/todo/domain/Todo.java
  src/main/java/com/ddudu/todo/dto/response/TodoResponse.java
  src/main/java/com/ddudu/todo/repository/TodoRepository.java
  src/main/java/com/ddudu/todo/service/TodoService.java
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
Labels: ✨feature

#22 회원가입 기능 구현
  build.gradle
  src/main/java/com/ddudu/config/JpaConfig.java
  src/main/java/com/ddudu/user/controller/UserController.java
  src/main/java/com/ddudu/user/domain/Email.java
  src/main/java/com/ddudu/user/domain/Password.java
  src/main/java/com/ddudu/user/domain/User.java
  src/main/java/com/ddudu/user/domain/UserStatus.java
  src/main/java/com/ddudu/user/dto/request/SignUpRequest.java
  src/main/java/com/ddudu/user/dto/response/SignUpResponse.java
  src/main/java/com/ddudu/user/repository/UserRepository.java
  src/main/java/com/ddudu/user/service/UserService.java
  src/main/resources/db/data/afterMigrate.sql
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/domain/UserTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: ✨feature

#38 회원가입 시 자기소개 추가
  src/main/java/com/ddudu/user/domain/User.java
  src/main/java/com/ddudu/user/dto/request/SignUpRequest.java
  src/main/java/com/ddudu/user/service/UserService.java
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/domain/UserTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: ✨feature

#40 일별 할 일 리스트 조회 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/ddudu/todo/controller/TodoController.java
  src/main/java/com/ddudu/todo/dto/response/GoalInfo.java
  src/main/java/com/ddudu/todo/dto/response/TodoInfo.java
  src/main/java/com/ddudu/todo/dto/response/TodoListResponse.java
  src/main/java/com/ddudu/todo/dto/response/TodoResponse.java
  src/main/java/com/ddudu/todo/repository/TodoRepository.java
  src/main/java/com/ddudu/todo/repository/TodoRepositoryCustom.java
  src/main/java/com/ddudu/todo/repository/TodoRepositoryImpl.java
  src/main/java/com/ddudu/todo/service/TodoService.java
  src/main/resources/db/data/afterMigrate.sql
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
Labels: ✨feature

#43 목표 수정 기능 구현
  src/main/java/com/ddudu/goal/controller/GoalController.java
  src/main/java/com/ddudu/goal/domain/Goal.java
  src/main/java/com/ddudu/goal/dto/requset/UpdateGoalRequest.java
  src/main/java/com/ddudu/goal/dto/response/GoalResponse.java
  src/main/java/com/ddudu/goal/service/GoalService.java
  src/main/resources/db/data/afterMigrate.sql
  src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
  src/test/java/com/ddudu/goal/domain/GoalTest.java
  src/test/java/com/ddudu/goal/service/GoalServiceTest.java
Labels: ✨feature

#46 할 일 상태 변경 기능 구현
  src/main/java/com/ddudu/todo/controller/TodoController.java
  src/main/java/com/ddudu/todo/domain/Todo.java
  src/main/java/com/ddudu/todo/dto/response/TodoInfo.java
  src/main/java/com/ddudu/todo/service/TodoService.java
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
Labels: ✨feature

#52 CI에 슬랙 알림 추가
  .github/workflows/ci-pipeline.yaml
Labels: ⚙setting

#56 BaseTimeEntity 생성 및 적용
  src/main/java/com/ddudu/common/BaseEntity.java
  src/main/java/com/ddudu/goal/domain/Goal.java
  src/main/java/com/ddudu/todo/domain/Todo.java
  src/main/java/com/ddudu/user/domain/User.java
Labels: 🛠refactor
