Repository DDu-Du-DDu-Du/back-end, pull requests merged in 2024-05, with the labels that each got.

#127 Feat/#116 modify ddl entity
  build.gradle
  src/main/java/com/ddudu/application/common/BaseEntity.java
  src/main/java/com/ddudu/application/common/domain/BaseDomain.java
  src/main/java/com/ddudu/application/goal/domain/Goal.java
  src/main/java/com/ddudu/application/goal/domain/GoalRepository.java
  src/main/java/com/ddudu/application/goal/service/GoalService.java
  src/main/java/com/ddudu/application/like/domain/Like.java
  src/main/java/com/ddudu/application/like/domain/LikeRepository.java
  src/main/java/com/ddudu/application/like/dto/response/LikeResponse.java
  src/main/java/com/ddudu/application/like/service/LikeService.java
  src/main/java/com/ddudu/application/todo/domain/Todo.java
  src/main/java/com/ddudu/application/todo/domain/TodoRepository.java
  src/main/java/com/ddudu/application/todo/service/TodoService.java
  src/main/java/com/ddudu/application/user/domain/Following.java
  src/main/java/com/ddudu/application/user/domain/FollowingRepository.java
  src/main/java/com/ddudu/application/user/domain/User.java
  src/main/java/com/ddudu/application/user/domain/UserRepository.java
  src/main/java/com/ddudu/persistence/dao/like/LikeDaoImpl.java
  src/main/java/com/ddudu/persistence/dao/user/FollowingDao.java
  src/main/java/com/ddudu/persistence/dao/user/UserDao.java
  src/main/java/com/ddudu/persistence/dao/user/UserDaoImpl.java
  src/main/java/com/ddudu/persistence/entity/AchievementEntity.java
  src/main/java/com/ddudu/persistence/entity/AuthProviderEntity.java
  src/main/java/com/ddudu/persistence/entity/CommentEntity.java
  src/main/java/com/ddudu/persistence/entity/FollowingEntity.java
  src/main/java/com/ddudu/persistence/entity/FollowingId.java
  src/main/java/com/ddudu/persistence/entity/GoalEntity.java
  src/main/java/com/ddudu/persistence/entity/LikeEntity.java
  src/main/java/com/ddudu/persistence/entity/NotificationEntity.java
  src/main/java/com/ddudu/persistence/entity/PeriodGoalEntity.java
  src/main/java/com/ddudu/persistence/entity/TagEntity.java
  src/main/java/com/ddudu/persistence/entity/TemplateEntity.java
  src/main/java/com/ddudu/persistence/entity/TemplateLikeEntity.java
  src/main/java/com/ddudu/persistence/entity/TemplateLikeId.java
  src/main/java/com/ddudu/persistence/entity/TemplateTodoEntity.java
  src/main/java/com/ddudu/persistence/entity/TodoEntity.java
  src/main/java/com/ddudu/persistence/entity/UserAchievementEntity.java
  src/main/java/com/ddudu/persistence/entity/UserEntity.java
  src/main/java/com/ddudu/persistence/repository/FollowingRepositoryImpl.java
  src/main/java/com/ddudu/persistence/repository/GoalRepositoryImpl.java
  src/main/java/com/ddudu/persistence/repository/LikeRepositoryImpl.java
  src/main/java/com/ddudu/persistence/repository/TodoRepositoryImpl.java
  src/main/java/com/ddudu/persistence/repository/UserRepositoryImpl.java
  src/main/java/com/ddudu/persistence/util/FakeValueGenerator.java
  src/main/resources/db/data/afterMigrate.sql
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/com/ddudu/auth/service/AuthServiceTest.java
  src/test/java/com/ddudu/goal/domain/GoalTest.java
  src/test/java/com/ddudu/goal/service/GoalServiceTest.java
  src/test/java/com/ddudu/like/service/LikeServiceTest.java
  src/test/java/com/ddudu/todo/domain/TodoTest.java
  src/test/java/com/ddudu/user/service/FollowingServiceTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: 🛠refactor, ✨feature

#137 목표 수정
  src/main/java/com/ddudu/application/domain/goal/domain/Goal.java
  src/main/java/com/ddudu/application/domain/goal/domain/enums/GoalStatus.java
  src/main/java/com/ddudu/application/domain/goal/dto/request/UpdateGoalRequest.java
  src/main/java/com/ddudu/application/domain/goal/exception/GoalErrorCode.java
  src/main/java/com/ddudu/application/port/in/UpdateGoalUseCase.java
  src/main/java/com/ddudu/application/port/out/UpdateGoalPort.java
  src/main/java/com/ddudu/application/service/UpdateGoalService.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/GoalPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/entity/GoalEntity.java
  src/main/java/com/ddudu/old/goal/dto/requset/UpdateGoalRequest.java
  src/main/java/com/ddudu/old/goal/service/GoalService.java
  src/main/java/com/ddudu/presentation/api/controller/GoalController.java
  src/test/java/com/ddudu/application/domain/goal/domain/GoalTest.java
  src/test/java/com/ddudu/application/service/UpdateGoalServiceTest.java
  src/test/java/com/ddudu/old/goal/controller/GoalControllerTest.java
  src/test/java/com/ddudu/old/goal/service/GoalServiceTest.java
Labels: 🛠refactor, ✨feature

#138 리프레시 토큰 구현
  .github/workflows/ci-pipeline.yaml
  src/main/java/com/ddudu/application/domain/authentication/domain/RefreshToken.java
  src/main/java/com/ddudu/application/domain/authentication/domain/vo/UserFamily.java
  src/main/java/com/ddudu/application/domain/authentication/dto/request/TokenRefreshRequest.java
  src/main/java/com/ddudu/application/domain/authentication/dto/response/TokenResponse.java
  src/main/java/com/ddudu/application/domain/authentication/exception/AuthErrorCode.java
  src/main/java/com/ddudu/application/domain/authentication/service/AuthDomainService.java
  src/main/java/com/ddudu/application/domain/authentication/service/JwtIssuer.java
  src/main/java/com/ddudu/application/domain/user/exception/UserErrorCode.java
  src/main/java/com/ddudu/application/port/in/auth/SocialLoginUseCase.java
  src/main/java/com/ddudu/application/port/in/auth/TokenRefreshUseCase.java
  src/main/java/com/ddudu/application/port/out/auth/SignUpPort.java
  src/main/java/com/ddudu/application/port/out/auth/SocialResourcePort.java
  src/main/java/com/ddudu/application/port/out/auth/TokenLoaderPort.java
  src/main/java/com/ddudu/application/port/out/auth/TokenManipulationPort.java
  src/main/java/com/ddudu/application/port/out/user/UserLoaderPort.java
  src/main/java/com/ddudu/application/service/auth/SocialLoginService.java
  src/main/java/com/ddudu/application/service/auth/TokenRefreshService.java
  src/main/java/com/ddudu/application/service/goal/CreateGoalService.java
  src/main/java/com/ddudu/application/service/goal/RetrieveAllGoalsService.java
  src/main/java/com/ddudu/application/service/goal/RetrieveGoalService.java
  src/main/java/com/ddudu/infrastructure/api/adapter/ExternalApiAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/TokenPersistenceAdpater.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/UserPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/config/QueryDslConfig.java
  src/main/java/com/ddudu/infrastructure/persistence/dto/FullUser.java
  src/main/java/com/ddudu/infrastructure/persistence/entity/RefreshTokenEntity.java
  src/main/java/com/ddudu/infrastructure/persistence/entity/RefreshTokenId.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/token/RefreshTokenQueryRepository.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/token/RefreshTokenQueryRepositoryImpl.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/token/RefreshTokenRepository.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/user/UserQueryRepository.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/user/UserQueryRepositoryImpl.java
  src/main/java/com/ddudu/presentation/api/controller/AuthController.java
  src/main/java/com/ddudu/presentation/api/controller/UserController.java
  src/main/java/com/ddudu/presentation/api/exception/GlobalExceptionHandler.java
  src/main/resources/db/migration/V3__add_refresh_token.sql
  src/test/java/com/ddudu/application/domain/authentication/domain/RefreshTokenTest.java
  src/test/java/com/ddudu/application/domain/authentication/domain/vo/UserFamilyTest.java
  src/test/java/com/ddudu/application/domain/authentication/service/AuthDomainServiceTest.java
  src/test/java/com/ddudu/application/domain/goal/domain/GoalTest.java
  src/test/java/com/ddudu/application/service/ChangeGoalStatusServiceTest.java
  src/test/java/com/ddudu/application/service/CreateGoalServiceTest.java
  src/test/java/com/ddudu/application/service/RetrieveAllGoalsServiceTest.java
  src/test/java/com/ddudu/application/service/RetrieveGoalServiceTest.java
  src/test/java/com/ddudu/application/service/SocialLoginServiceTest.java
  src/test/java/com/ddudu/application/service/TokenRefreshServiceTest.java
  src/test/java/com/ddudu/application/service/UpdateGoalServiceTest.java
  src/test/java/com/ddudu/old/user/controller/UserControllerTest.java
Labels: ✨feature

#142 내 정보 불러오기 구현
  .github/workflows/cd-dev.yaml
  .github/workflows/cd-pipeline.yaml
  src/main/java/com/ddudu/application/domain/user/dto/MeResponse.java
  src/main/java/com/ddudu/application/domain/user/exception/UserErrorCode.java
  src/main/java/com/ddudu/application/port/in/user/GetMyInfoUseCase.java
  src/main/java/com/ddudu/application/port/out/user/UserLoaderPort.java
  src/main/java/com/ddudu/application/service/auth/TokenRefreshService.java
  src/main/java/com/ddudu/application/service/goal/CreateGoalService.java
  src/main/java/com/ddudu/application/service/goal/RetrieveAllGoalsService.java
  src/main/java/com/ddudu/application/service/user/GetMyInfoService.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/UserPersistenceAdapter.java
  src/main/java/com/ddudu/presentation/api/annotation/Login.java
  src/main/java/com/ddudu/presentation/api/config/SwaggerConfig.java
  src/main/java/com/ddudu/presentation/api/controller/AuthController.java
  src/main/java/com/ddudu/presentation/api/controller/GoalController.java
  src/main/java/com/ddudu/presentation/api/controller/UserController.java
  src/test/java/com/ddudu/application/domain/goal/domain/GoalTest.java
  src/test/java/com/ddudu/application/service/user/GetMyInfoServiceTest.java
Labels: ✨feature

#152 예외 코드 수정 및 슬랙 알림 오타 수정
  .github/workflows/cd-dev.yaml
  .github/workflows/cd-pipeline.yaml
  src/main/java/com/ddudu/application/domain/authentication/exception/AuthErrorCode.java
  src/main/java/com/ddudu/old/auth/dto/response/MeResponse.java
  src/main/java/com/ddudu/old/auth/service/AuthService.java
  src/main/java/com/ddudu/presentation/api/exception/GlobalExceptionHandler.java
  src/main/java/com/ddudu/presentation/api/exception/InvalidAuthenticationException.java
  src/main/java/com/ddudu/presentation/api/exception/InvalidTokenException.java
  src/main/java/com/ddudu/presentation/api/resolver/LoginUserArgumentResolver.java
  src/test/java/com/ddudu/old/auth/controller/AuthControllerTest.java
  src/test/java/com/ddudu/old/auth/jwt/JwtAuthTokenTest.java
  src/test/java/com/ddudu/old/resolver/LoginUserArgumentResolverTest.java
Labels: 🚨bugfix, 🛠refactor, ✨feature

#149 뚜두 도메인 마이그레이션
  src/main/java/com/ddudu/application/domain/ddudu/domain/Ddudu.java
  src/main/java/com/ddudu/application/domain/ddudu/domain/enums/DduduStatus.java
  src/main/java/com/ddudu/application/domain/ddudu/exception/DduduErrorCode.java
  src/main/java/com/ddudu/infrastructure/persistence/entity/DduduEntity.java
  src/main/java/com/ddudu/infrastructure/persistence/entity/GoalEntity.java
  src/main/java/com/ddudu/infrastructure/persistence/entity/UserEntity.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepository.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduRepository.java
  src/main/java/com/ddudu/old/like/domain/Like.java
  src/main/java/com/ddudu/old/like/domain/LikeRepository.java
  src/main/java/com/ddudu/old/like/dto/response/LikeResponse.java
  src/main/java/com/ddudu/old/like/service/LikeService.java
  src/main/java/com/ddudu/old/persistence/dao/like/LikeDao.java
  src/main/java/com/ddudu/old/persistence/dao/like/LikeDaoCustom.java
  src/main/java/com/ddudu/old/persistence/dao/like/LikeDaoImpl.java
  src/main/java/com/ddudu/old/persistence/entity/LikeEntity.java
  src/main/java/com/ddudu/old/persistence/entity/TodoEntity.java
  src/main/java/com/ddudu/old/persistence/repository/LikeRepositoryImpl.java
  src/main/java/com/ddudu/old/persistence/repository/TodoRepositoryImpl.java
  src/main/java/com/ddudu/old/todo/domain/OldTodoRepository.java
  src/main/java/com/ddudu/old/todo/domain/Todo.java
  src/main/java/com/ddudu/old/todo/domain/TodoStatus.java
  src/main/java/com/ddudu/old/todo/dto/response/TodoInfo.java
  src/main/java/com/ddudu/old/todo/dto/response/TodoResponse.java
  src/main/java/com/ddudu/old/todo/service/TodoService.java
  src/main/java/com/ddudu/presentation/api/exception/ErrorCodeParser.java
  src/main/resources/db/migration/V4__change_ddudu_date_time.sql
  src/test/java/com/ddudu/application/domain/ddudu/domain/DduduTest.java
  src/test/java/com/ddudu/application/service/goal/DeleteGoalServiceTest.java
  src/test/java/com/ddudu/fixture/DduduFixture.java
  src/test/java/com/ddudu/old/like/domain/LikeTest.java
  src/test/java/com/ddudu/old/like/service/LikeServiceTest.java
  src/test/java/com/ddudu/old/todo/controller/DduduControllerTest.java
  src/test/java/com/ddudu/old/todo/domain/TodoTest.java
  src/test/java/com/ddudu/old/todo/service/DduduServiceTest.java
Labels: 🛠refactor

#154 뚜두의 시작/종료 시간 설정
  src/main/java/com/ddudu/application/domain/ddudu/domain/Ddudu.java
  src/main/java/com/ddudu/application/domain/ddudu/dto/request/PeriodSetupRequest.java
  src/main/java/com/ddudu/application/port/in/ddudu/PeriodSetupUseCase.java
  src/main/java/com/ddudu/application/port/out/ddudu/DduduLoaderPort.java
  src/main/java/com/ddudu/application/port/out/ddudu/PeriodSetupPort.java
  src/main/java/com/ddudu/application/port/out/ddudu/SaveDduduPort.java
  src/main/java/com/ddudu/application/service/ddudu/PeriodSetupService.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/entity/DduduEntity.java
  src/main/java/com/ddudu/old/todo/service/TodoService.java
  src/main/java/com/ddudu/presentation/api/controller/DduduController.java
  src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
  src/main/resources/db/data/afterMigrate.sql
  src/test/java/com/ddudu/application/domain/ddudu/domain/DduduTest.java
  src/test/java/com/ddudu/application/service/ddudu/DduduPeriodSetupServiceTest.java
  src/test/java/com/ddudu/fixture/DduduFixture.java
  src/test/java/com/ddudu/old/todo/controller/DduduControllerTest.java
  src/test/java/com/ddudu/old/user/controller/UserControllerTest.java
Labels: ✨feature

#160 뚜두 미루기, 오늘하기용 날짜 변경 API 문서
  src/main/java/com/ddudu/application/domain/ddudu/dto/request/MoveDateRequest.java
  src/main/java/com/ddudu/presentation/api/controller/DduduController.java
  src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
Labels: ✨feature

#163 뚜두 다른 날 반복하기 문서 추가
  src/main/java/com/ddudu/application/domain/ddudu/dto/request/RepeatAnotherDayRequest.java
  src/main/java/com/ddudu/application/domain/ddudu/dto/response/RepeatAnotherDayResponse.java
  src/main/java/com/ddudu/presentation/api/controller/DduduController.java
  src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
Labels: ✨feature

#164 뚜두 다른 날 반복하기 (다시하기) 구현
  src/main/java/com/ddudu/application/domain/ddudu/domain/Ddudu.java
  src/main/java/com/ddudu/application/domain/ddudu/exception/DduduErrorCode.java
  src/main/java/com/ddudu/application/port/in/ddudu/RepeatUseCase.java
  src/main/java/com/ddudu/application/port/out/ddudu/RepeatDduduPort.java
  src/main/java/com/ddudu/application/service/ddudu/RepeatService.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
  src/main/java/com/ddudu/presentation/api/controller/DduduController.java
  src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
  src/test/java/com/ddudu/application/domain/ddudu/domain/DduduTest.java
  src/test/java/com/ddudu/application/service/ddudu/RepeatServiceTest.java
Labels: ✨feature

#168 뚜두 목록 조회 구현
  src/main/java/com/ddudu/application/dto/ddudu/DduduCursorDto.java
  src/main/java/com/ddudu/application/dto/ddudu/request/DduduSearchRequest.java
  src/main/java/com/ddudu/application/dto/scroll/OrderType.java
  src/main/java/com/ddudu/application/dto/scroll/request/ScrollRequest.java
  src/main/java/com/ddudu/application/port/in/ddudu/DduduSearchUseCase.java
  src/main/java/com/ddudu/application/port/out/ddudu/DduduSearchPort.java
  src/main/java/com/ddudu/application/port/out/ddudu/SaveDduduPort.java
  src/main/java/com/ddudu/application/port/out/user/UserLoaderPort.java
  src/main/java/com/ddudu/application/service/ddudu/DduduSearchService.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/UserPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/dto/DduduCursorDto.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepository.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java
  src/main/java/com/ddudu/presentation/api/controller/DduduController.java
  src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
  src/test/java/com/ddudu/application/service/ddudu/DduduSearchServiceTest.java
  src/test/java/com/ddudu/fixture/DduduFixture.java
Labels: ✨feature

#167 뚜두 목록 조회 구현
  src/main/java/com/ddudu/application/dto/ddudu/SimpleDduduSearchDto.java
  src/main/java/com/ddudu/application/dto/ddudu/request/DduduSearchRequest.java
  src/main/java/com/ddudu/application/dto/scroll/OrderType.java
  src/main/java/com/ddudu/application/dto/scroll/request/ScrollRequest.java
  src/main/java/com/ddudu/application/dto/scroll/response/ScrollResponse.java
  src/main/java/com/ddudu/application/port/in/ddudu/DduduSearchUseCase.java
  src/main/java/com/ddudu/application/port/out/ddudu/DduduSearchPort.java
  src/main/java/com/ddudu/application/port/out/ddudu/SaveDduduPort.java
  src/main/java/com/ddudu/application/port/out/user/UserLoaderPort.java
  src/main/java/com/ddudu/application/service/ddudu/DduduSearchService.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/UserPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/dto/DduduCursorDto.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepository.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java
  src/main/java/com/ddudu/presentation/api/controller/DduduController.java
  src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
  src/test/java/com/ddudu/application/service/ddudu/DduduSearchServiceTest.java
  src/test/java/com/ddudu/fixture/DduduFixture.java
Labels: ✨feature

#170 뚜두 생성 기능
  src/main/java/com/ddudu/application/domain/ddudu/exception/DduduErrorCode.java
  src/main/java/com/ddudu/application/domain/ddudu/service/DduduDomainService.java
  src/main/java/com/ddudu/application/dto/ddudu/request/CreateDduduRequest.java
  src/main/java/com/ddudu/application/port/in/ddudu/CreateDduduUseCase.java
  src/main/java/com/ddudu/application/service/ddudu/CreateDduduService.java
  src/main/java/com/ddudu/old/todo/dto/request/CreateTodoRequest.java
  src/main/java/com/ddudu/old/todo/service/TodoService.java
  src/main/java/com/ddudu/presentation/api/common/dto/response/IdResponse.java
  src/main/java/com/ddudu/presentation/api/controller/DduduController.java
  src/main/java/com/ddudu/presentation/api/doc/DduduControllerDoc.java
  src/test/java/com/ddudu/application/domain/ddudu/service/DduduDomainServiceTest.java
  src/test/java/com/ddudu/application/service/ddudu/CreateDduduServiceTest.java
  src/test/java/com/ddudu/old/todo/service/DduduServiceTest.java
Labels: ✨feature
