Repository DDu-Du-DDu-Du/back-end, pull requests merged in 2024-01, with the labels that each got.

#48 목표 조회(단일, 전체) 기능 구현
  src/main/java/com/ddudu/goal/controller/GoalController.java
  src/main/java/com/ddudu/goal/domain/Goal.java
  src/main/java/com/ddudu/goal/dto/response/GoalResponse.java
  src/main/java/com/ddudu/goal/dto/response/GoalSummaryResponse.java
  src/main/java/com/ddudu/goal/repository/GoalRepository.java
  src/main/java/com/ddudu/goal/service/GoalService.java
  src/main/resources/db/data/afterMigrate.sql
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
  src/test/java/com/ddudu/goal/domain/GoalTest.java
  src/test/java/com/ddudu/goal/service/GoalServiceTest.java
  src/test/java/com/ddudu/todo/domain/TodoTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
Labels: ✨feature

#51 주간 및 월간 할 일 달성률 조회 기능 구현
  src/main/java/com/ddudu/todo/controller/TodoController.java
  src/main/java/com/ddudu/todo/dto/response/TodoCompletionResponse.java
  src/main/java/com/ddudu/todo/repository/TodoRepositoryCustom.java
  src/main/java/com/ddudu/todo/repository/TodoRepositoryImpl.java
  src/main/java/com/ddudu/todo/service/TodoService.java
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
Labels: ✨feature

#50 예외 구조화 및 전역 예외 처리
  src/main/java/com/ddudu/common/exception/BadRequestException.java
  src/main/java/com/ddudu/common/exception/BusinessException.java
  src/main/java/com/ddudu/common/exception/DataNotFoundException.java
  src/main/java/com/ddudu/common/exception/DuplicateResourceException.java
  src/main/java/com/ddudu/common/exception/ErrorCode.java
  src/main/java/com/ddudu/common/exception/ErrorResponse.java
  src/main/java/com/ddudu/common/exception/GeneralExceptionHandler.java
  src/main/java/com/ddudu/common/exception/InvalidParameterException.java
  src/main/java/com/ddudu/goal/controller/GoalController.java
  src/main/java/com/ddudu/goal/domain/Color.java
  src/main/java/com/ddudu/goal/domain/Goal.java
  src/main/java/com/ddudu/goal/dto/response/ErrorResponse.java
  src/main/java/com/ddudu/goal/exception/GoalErrorCode.java
  src/main/java/com/ddudu/goal/service/GoalService.java
  src/main/java/com/ddudu/todo/controller/TodoController.java
  src/main/java/com/ddudu/todo/domain/Todo.java
  src/main/java/com/ddudu/todo/exception/TodoErrorCode.java
  src/main/java/com/ddudu/todo/service/TodoService.java
  src/main/java/com/ddudu/user/domain/Email.java
  src/main/java/com/ddudu/user/domain/Password.java
  src/main/java/com/ddudu/user/domain/User.java
  src/main/java/com/ddudu/user/exception/UserErrorCode.java
  src/main/java/com/ddudu/user/service/UserService.java
  src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
  src/test/java/com/ddudu/goal/domain/GoalTest.java
  src/test/java/com/ddudu/goal/service/GoalServiceTest.java
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/todo/domain/TodoTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
  src/test/java/com/ddudu/user/domain/UserTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: 🛠refactor

#60 할 일 생성 기능 구현
  src/main/java/com/ddudu/goal/domain/Goal.java
  src/main/java/com/ddudu/todo/controller/TodoController.java
  src/main/java/com/ddudu/todo/domain/Todo.java
  src/main/java/com/ddudu/todo/dto/request/CreateTodoRequest.java
  src/main/java/com/ddudu/todo/exception/TodoErrorCode.java
  src/main/java/com/ddudu/todo/service/TodoService.java
  src/main/resources/db/data/afterMigrate.sql
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
  src/test/java/com/ddudu/goal/domain/GoalTest.java
  src/test/java/com/ddudu/goal/service/GoalServiceTest.java
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/todo/domain/TodoTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: ✨feature

#64 로그백 간단 설정
  src/main/resources/application-local.yaml
Labels: ⚙setting

#53 JWT 사용자 확인 구현
  src/main/java/com/ddudu/auth/controller/AuthController.java
  src/main/java/com/ddudu/auth/domain/authority/Authority.java
  src/main/java/com/ddudu/auth/exception/AuthErrorCode.java
  src/main/java/com/ddudu/auth/jwt/JwtAuthToken.java
  src/main/java/com/ddudu/auth/jwt/converter/JwtAuthorityConverter.java
  src/main/java/com/ddudu/auth/jwt/converter/JwtConverter.java
  src/main/java/com/ddudu/auth/service/AuthService.java
  src/main/java/com/ddudu/common/exception/BadCredentialsException.java
  src/main/java/com/ddudu/common/exception/GeneralExceptionHandler.java
  src/main/java/com/ddudu/common/exception/InvalidAuthenticationException.java
  src/main/java/com/ddudu/common/exception/InvalidTokenException.java
  src/main/java/com/ddudu/config/WebSecurityConfig.java
  src/main/java/com/ddudu/user/controller/UserController.java
  src/main/java/com/ddudu/user/dto/response/UserResponse.java
  src/main/java/com/ddudu/user/exception/UserErrorCode.java
  src/main/java/com/ddudu/user/service/UserService.java
  src/test/java/com/ddudu/auth/controller/AuthControllerTest.java
  src/test/java/com/ddudu/auth/jwt/JwtAuthTokenTest.java
  src/test/java/com/ddudu/auth/service/AuthServiceTest.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/domain/UserTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: ✨feature

#62 친구 테이블 작성 및 엔티티 정의
  src/main/java/com/ddudu/following/domain/Following.java
  src/main/java/com/ddudu/following/domain/FollowingStatus.java
  src/main/java/com/ddudu/following/exception/FollowingErrorCode.java
  src/main/java/com/ddudu/goal/domain/Goal.java
  src/main/java/com/ddudu/todo/domain/Todo.java
  src/main/java/com/ddudu/user/domain/User.java
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/com/ddudu/following/domain/FollowingTest.java
Labels: ✨feature

#58 목표 삭제 기능 구현
  src/main/java/com/ddudu/common/BaseEntity.java
  src/main/java/com/ddudu/goal/controller/GoalController.java
  src/main/java/com/ddudu/goal/domain/Goal.java
  src/main/java/com/ddudu/goal/repository/GoalRepository.java
  src/main/java/com/ddudu/goal/repository/GoalRepositoryCustom.java
  src/main/java/com/ddudu/goal/repository/GoalRepositoryImpl.java
  src/main/java/com/ddudu/goal/service/GoalService.java
  src/main/java/com/ddudu/todo/domain/Todo.java
  src/main/java/com/ddudu/user/domain/User.java
  src/main/java/com/ddudu/user/dto/request/SignUpRequest.java
  src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
  src/test/java/com/ddudu/goal/domain/GoalTest.java
  src/test/java/com/ddudu/goal/service/GoalServiceTest.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
Labels: ✨feature

#72 @Login 애너테이션 구현
  src/main/java/com/ddudu/auth/exception/AuthErrorCode.java
  src/main/java/com/ddudu/common/annotation/Login.java
  src/main/java/com/ddudu/common/annotation/LoginUserArgumentResolver.java
  src/main/java/com/ddudu/config/WebConfig.java
  src/main/java/com/ddudu/user/controller/UserController.java
Labels: 🛠refactor

#79 할 일 삭제 기능 구현
  src/main/java/com/ddudu/common/exception/ForbiddenException.java
  src/main/java/com/ddudu/common/exception/GeneralExceptionHandler.java
  src/main/java/com/ddudu/todo/controller/TodoController.java
  src/main/java/com/ddudu/todo/exception/TodoErrorCode.java
  src/main/java/com/ddudu/todo/service/TodoService.java
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
Labels: ✨feature

#66 할 일 리팩토링
  src/main/java/com/ddudu/todo/controller/TodoController.java
  src/main/java/com/ddudu/todo/domain/Todo.java
  src/main/java/com/ddudu/todo/repository/TodoRepositoryCustom.java
  src/main/java/com/ddudu/todo/repository/TodoRepositoryImpl.java
  src/main/java/com/ddudu/todo/service/TodoService.java
  src/main/resources/db/data/afterMigrate.sql
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/todo/domain/TodoTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
Labels: 🛠refactor

#76 목표 공개 설정 변경 기능 구현
  src/main/java/com/ddudu/goal/controller/GoalController.java
  src/main/java/com/ddudu/goal/domain/Goal.java
  src/main/java/com/ddudu/goal/service/GoalService.java
  src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
  src/test/java/com/ddudu/goal/service/GoalServiceTest.java
Labels: ✨feature

#74 이메일 및 비밀번호 변경 기능 구현
  src/main/java/com/ddudu/user/controller/UserController.java
  src/main/java/com/ddudu/user/domain/User.java
  src/main/java/com/ddudu/user/dto/request/UpdateEmailRequest.java
  src/main/java/com/ddudu/user/dto/request/UpdatePasswordRequest.java
  src/main/java/com/ddudu/user/dto/response/UpdatePasswordResponse.java
  src/main/java/com/ddudu/user/exception/UserErrorCode.java
  src/main/java/com/ddudu/user/service/UserService.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: ✨feature

#81 CI 수정
  .github/workflows/ci-pipeline.yaml
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
Labels: ⚙setting

#67 팔로잉 기능 구현
  src/main/java/com/ddudu/config/WebSecurityConfig.java
  src/main/java/com/ddudu/following/controller/FollowingController.java
  src/main/java/com/ddudu/following/dto/request/FollowRequest.java
  src/main/java/com/ddudu/following/dto/response/FollowResponse.java
  src/main/java/com/ddudu/following/exception/FollowingErrorCode.java
  src/main/java/com/ddudu/following/repository/FollowingRepository.java
  src/main/java/com/ddudu/following/service/FollowingService.java
  src/main/java/com/ddudu/user/dto/request/SignUpRequest.java
  src/main/resources/db/data/afterMigrate.sql
  src/test/java/com/ddudu/following/controller/FollowingControllerTest.java
  src/test/java/com/ddudu/following/service/FollowingServiceTest.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/domain/UserTest.java
Labels: ✨feature

#68 사용자에 팔로우 허락 옵션 추가
  src/main/java/com/ddudu/following/dto/response/FollowResponse.java
  src/main/java/com/ddudu/following/service/FollowingService.java
  src/main/java/com/ddudu/user/domain/Options.java
  src/main/java/com/ddudu/user/domain/User.java
  src/main/resources/db/data/afterMigrate.sql
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/com/ddudu/following/service/FollowingServiceTest.java
  src/test/java/com/ddudu/user/domain/OptionsTest.java
Labels: ✨feature

#73 프로필 수정 기능 구현
  src/main/java/com/ddudu/user/controller/UserController.java
  src/main/java/com/ddudu/user/domain/User.java
  src/main/java/com/ddudu/user/dto/request/UpdateProfileRequest.java
  src/main/java/com/ddudu/user/dto/response/UserProfileResponse.java
  src/main/java/com/ddudu/user/exception/UserErrorCode.java
  src/main/java/com/ddudu/user/service/UserService.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/domain/UserTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: ✨feature

#83 팔로잉 신청 수락/무시 구현
  src/main/java/com/ddudu/following/controller/FollowingController.java
  src/main/java/com/ddudu/following/domain/Following.java
  src/main/java/com/ddudu/following/domain/FollowingStatus.java
  src/main/java/com/ddudu/following/dto/request/UpdateFollowingRequest.java
  src/main/java/com/ddudu/following/dto/response/FollowingResponse.java
  src/main/java/com/ddudu/following/exception/FollowingErrorCode.java
  src/main/java/com/ddudu/following/service/FollowingService.java
  src/test/java/com/ddudu/following/controller/FollowingControllerTest.java
  src/test/java/com/ddudu/following/domain/FollowingTest.java
  src/test/java/com/ddudu/following/service/FollowingServiceTest.java
Labels: ✨feature

#89 할 일 수정 기능 구현
  src/main/java/com/ddudu/goal/domain/Goal.java
  src/main/java/com/ddudu/todo/controller/TodoController.java
  src/main/java/com/ddudu/todo/domain/Todo.java
  src/main/java/com/ddudu/todo/dto/request/UpdateTodoRequest.java
  src/main/java/com/ddudu/todo/service/TodoService.java
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
  src/test/java/com/ddudu/user/domain/UserTest.java
Labels: ✨feature

#87 팔로잉 삭제 구현
  src/main/java/com/ddudu/following/controller/FollowingController.java
  src/main/java/com/ddudu/following/service/FollowingService.java
  src/test/java/com/ddudu/following/controller/FollowingControllerTest.java
  src/test/java/com/ddudu/following/service/FollowingServiceTest.java
  src/test/java/com/ddudu/goal/service/GoalServiceTest.java
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: ✨feature

#96 사용자 옵션 토글
  src/main/java/com/ddudu/following/domain/Following.java
  src/main/java/com/ddudu/user/controller/UserController.java
  src/main/java/com/ddudu/user/domain/Options.java
  src/main/java/com/ddudu/user/domain/User.java
  src/main/java/com/ddudu/user/dto/response/ToggleOptionResponse.java
  src/main/java/com/ddudu/user/service/UserService.java
  src/test/java/com/ddudu/following/service/FollowingServiceTest.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/domain/OptionsTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: ✨feature

#86 Goal 관련 기능 권한 설정 및 테스트 코드 리팩토링
  src/main/java/com/ddudu/common/resolver/LoginUserArgumentResolver.java
  src/main/java/com/ddudu/config/WebConfig.java
  src/main/java/com/ddudu/goal/controller/GoalController.java
  src/main/java/com/ddudu/goal/exception/GoalErrorCode.java
  src/main/java/com/ddudu/goal/service/GoalService.java
  src/test/java/com/ddudu/common/resolver/LoginUserArgumentResolverTest.java
  src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
  src/test/java/com/ddudu/goal/service/GoalServiceTest.java
Labels: 🛠refactor, ✨feature

#104 Rest Docs 설정 및 컨트롤러 테스트 환경 분리
  build.gradle
  src/test/java/com/ddudu/auth/controller/AuthControllerTest.java
  src/test/java/com/ddudu/auth/service/AuthServiceTest.java
  src/test/java/com/ddudu/following/controller/FollowingControllerTest.java
  src/test/java/com/ddudu/goal/controller/GoalControllerTest.java
  src/test/java/com/ddudu/support/ControllerTestSupport.java
  src/test/java/com/ddudu/support/RestDocsSupport.java
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
Labels: 🛠refactor, ✨feature

#93 할 일 좋아요 관련 기능 구현
  src/main/java/com/ddudu/common/BaseEntity.java
  src/main/java/com/ddudu/like/controller/LikeController.java
  src/main/java/com/ddudu/like/domain/Like.java
  src/main/java/com/ddudu/like/dto/request/LikeRequest.java
  src/main/java/com/ddudu/like/dto/response/LikeResponse.java
  src/main/java/com/ddudu/like/exception/LikeErrorCode.java
  src/main/java/com/ddudu/like/repository/LikeRepository.java
  src/main/java/com/ddudu/like/repository/LikeRepositoryCustom.java
  src/main/java/com/ddudu/like/repository/LikeRepositoryImpl.java
  src/main/java/com/ddudu/like/service/LikeService.java
  src/main/java/com/ddudu/todo/dto/response/LikeInfo.java
  src/main/java/com/ddudu/todo/dto/response/TodoInfo.java
  src/main/java/com/ddudu/todo/service/TodoService.java
  src/main/resources/db/data/afterMigrate.sql
  src/main/resources/db/migration/V1__schema.sql
  src/test/java/com/ddudu/like/controller/LikeControllerTest.java
  src/test/java/com/ddudu/like/domain/LikeTest.java
  src/test/java/com/ddudu/like/service/LikeServiceTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
Labels: ✨feature

#107 유저 리팩터링
  src/main/java/com/ddudu/user/controller/UserController.java
  src/main/java/com/ddudu/user/domain/Email.java
  src/main/java/com/ddudu/user/domain/Options.java
  src/main/java/com/ddudu/user/domain/Password.java
  src/main/java/com/ddudu/user/domain/User.java
  src/main/java/com/ddudu/user/service/UserService.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/domain/UserTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: 🛠refactor

#110 docs: README 파일 생성
  README.md
Labels: 📃docs

#111 docs: README.md 오타 수정
  README.md
Labels: 📃docs

#113 팔로잉 요청 받은 사용자가 수락/무시 할 수 없던 버그 수정
  src/main/java/com/ddudu/user/domain/Following.java
  src/main/java/com/ddudu/user/exception/FollowingErrorCode.java
  src/main/java/com/ddudu/user/service/FollowingService.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/service/FollowingServiceTest.java
Labels: 🚨bugfix

#99 사용자 검색 기능 구현
  src/main/java/com/ddudu/user/controller/UserController.java
  src/main/java/com/ddudu/user/domain/Email.java
  src/main/java/com/ddudu/user/domain/UserSearchType.java
  src/main/java/com/ddudu/user/repository/UserRepositoryCustom.java
  src/main/java/com/ddudu/user/repository/UserRepositoryImpl.java
  src/main/java/com/ddudu/user/service/UserService.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: ✨feature

#108 팔로워 조회 기능 구현
  src/main/java/com/ddudu/user/controller/UserController.java
  src/main/java/com/ddudu/user/dto/FollowingSearchType.java
  src/main/java/com/ddudu/user/repository/UserRepositoryCustom.java
  src/main/java/com/ddudu/user/repository/UserRepositoryImpl.java
  src/main/java/com/ddudu/user/service/UserService.java
  src/test/java/com/ddudu/auth/service/AuthServiceTest.java
  src/test/java/com/ddudu/user/controller/UserControllerTest.java
  src/test/java/com/ddudu/user/service/UserServiceTest.java
Labels: 🛠refactor, ✨feature

#109 할 일 전체적인 리팩토링
  src/main/java/com/ddudu/todo/controller/TodoController.java
  src/main/java/com/ddudu/todo/dto/response/TodoCompletionResponse.java
  src/main/java/com/ddudu/todo/dto/response/TodoListResponse.java
  src/main/java/com/ddudu/todo/dto/response/TodoResponse.java
  src/main/java/com/ddudu/todo/repository/TodoRepositoryImpl.java
  src/main/java/com/ddudu/todo/service/TodoService.java
  src/test/java/com/ddudu/todo/controller/TodoControllerTest.java
  src/test/java/com/ddudu/todo/service/TodoServiceTest.java
Labels: 🛠refactor
