Repository DDu-Du-DDu-Du/back-end, pull requests merged in 2024-08, with the labels that each got.

#219 반복 뚜두 수정 기능 구현
  src/main/java/com/ddudu/application/domain/repeat_ddudu/domain/RepeatDdudu.java
  src/main/java/com/ddudu/application/domain/repeat_ddudu/exception/RepeatDduduErrorCode.java
  src/main/java/com/ddudu/application/domain/repeat_ddudu/service/RepeatDduduDomainService.java
  src/main/java/com/ddudu/application/dto/goal/request/ChangeGoalStatusRequest.java
  src/main/java/com/ddudu/application/dto/repeat_ddudu/request/UpdateRepeatDduduRequest.java
  src/main/java/com/ddudu/application/port/in/repeat_ddudu/UpdateRepeatDduduUseCase.java
  src/main/java/com/ddudu/application/port/out/ddudu/DeleteDduduPort.java
  src/main/java/com/ddudu/application/port/out/repeat_ddudu/RepeatDduduLoaderPort.java
  src/main/java/com/ddudu/application/port/out/repeat_ddudu/UpdateRepeatDduduPort.java
  src/main/java/com/ddudu/application/service/repeat_ddudu/UpdateRepeatDduduService.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/RepeatDduduPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/entity/RepeatDduduEntity.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepository.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java
  src/main/java/com/ddudu/presentation/api/controller/RepeatDduduController.java
  src/main/java/com/ddudu/presentation/api/doc/RepeatDduduControllerDoc.java
  src/main/java/com/ddudu/presentation/api/doc/error/RepeatDduduErrorExamples.java
  src/test/java/com/ddudu/application/service/repeat_ddudu/UpdateRepeatDduduServiceTest.java
Labels: ✨feature

#220 목표 생성 시 반복 뚜두도 함께 생성할 수 있도록 변경
  src/main/java/com/ddudu/application/domain/repeat_ddudu/service/RepeatDduduDomainService.java
  src/main/java/com/ddudu/application/dto/goal/request/CreateGoalRequest.java
  src/main/java/com/ddudu/application/dto/goal/request/CreateRepeatDduduRequestWithoutGoal.java
  src/main/java/com/ddudu/application/dto/repeat_ddudu/RepeatPatternDto.java
  src/main/java/com/ddudu/application/service/goal/CreateGoalService.java
  src/test/java/com/ddudu/application/domain/goal/service/GoalDomainServiceTest.java
  src/test/java/com/ddudu/application/service/goal/CreateGoalServiceTest.java
Labels: ✨feature

#187 월별 뚜두 종합 통계 구현
  src/main/java/com/ddudu/application/domain/ddudu/service/DduduDomainService.java
  src/main/java/com/ddudu/application/dto/ddudu/StatsBaseDto.java
  src/main/java/com/ddudu/application/dto/goal/MonthlyStatsSummaryDto.java
  src/main/java/com/ddudu/application/dto/goal/response/GoalStatsCompletionNumberResponse.java
  src/main/java/com/ddudu/application/dto/goal/response/MonthlyStatsSummaryResponse.java
  src/main/java/com/ddudu/application/port/in/ddudu/CollectMonthlyStatsSummaryUseCase.java
  src/main/java/com/ddudu/application/port/out/goal/MonthlyStatsPort.java
  src/main/java/com/ddudu/application/service/ddudu/CollectMonthlyStatsSummaryService.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepository.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java
  src/main/java/com/ddudu/presentation/api/controller/GoalController.java
  src/main/java/com/ddudu/presentation/api/controller/StatsController.java
  src/main/java/com/ddudu/presentation/api/doc/GoalControllerDoc.java
  src/main/java/com/ddudu/presentation/api/doc/StatsControllerDoc.java
  src/main/resources/db/data/afterMigrate.sql
  src/test/java/com/ddudu/application/domain/ddudu/service/DduduDomainServiceTest.java
  src/test/java/com/ddudu/application/service/goal/CollectNumberStatsServiceTest.java
  src/test/java/com/ddudu/fixture/DduduFixture.java
  src/test/java/com/ddudu/fixture/GoalFixture.java
Labels: ✨feature

#222 뚜두 통합 통계 문서 디테일 추가
  src/main/java/com/ddudu/application/domain/ddudu/service/DduduDomainService.java
  src/main/java/com/ddudu/application/dto/stats/MonthlyStatsSummaryDto.java
  src/main/java/com/ddudu/application/dto/stats/StatsBaseDto.java
  src/main/java/com/ddudu/application/dto/stats/response/MonthlyStatsSummaryResponse.java
  src/main/java/com/ddudu/application/port/in/ddudu/CollectMonthlyStatsSummaryUseCase.java
  src/main/java/com/ddudu/application/port/out/goal/MonthlyStatsPort.java
  src/main/java/com/ddudu/application/service/ddudu/CollectMonthlyStatsSummaryService.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/DduduPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepository.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java
  src/main/java/com/ddudu/presentation/api/controller/StatsController.java
  src/main/java/com/ddudu/presentation/api/doc/StatsControllerDoc.java
  src/test/java/com/ddudu/application/domain/ddudu/service/DduduDomainServiceTest.java
  src/test/java/com/ddudu/application/service/ddudu/CollectNumberStatsServiceTest.java
Labels: 🚨bugfix, 📃docs, 📂rename

#226 반복 뚜두 응답 형식 변경
  src/main/java/com/ddudu/application/domain/repeat_ddudu/domain/RepeatPattern.java
Labels: ✨feature

#228 RepeatPattern 객체를 직렬화하지 못하는 오류 해결
  src/main/java/com/ddudu/infrastructure/persistence/converter/RepeatPatternConverter.java
Labels: 🚨bugfix

#230 fix: 목표 삭제 시 반복 뚜두가 남아있어 삭제가 되지 않는 오류 해결
  src/main/java/com/ddudu/application/port/out/repeat_ddudu/DeleteRepeatDduduPort.java
  src/main/java/com/ddudu/application/service/goal/DeleteGoalService.java
  src/main/java/com/ddudu/infrastructure/persistence/adapter/RepeatDduduPersistenceAdapter.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/ddudu/DduduQueryRepositoryImpl.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/repeat_ddudu/RepeatDduduQueryRepository.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/repeat_ddudu/RepeatDduduQueryRepositoryImpl.java
  src/main/java/com/ddudu/infrastructure/persistence/repository/repeat_ddudu/RepeatDduduRepository.java
Labels: 🚨bugfix
